<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $report['title'] ?? 'POS Report' }}</title>
    <style>
        @page { margin: 18px; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #111827; }
        h1 { font-size: 18px; margin: 0 0 6px; }
        .meta { margin-bottom: 10px; color: #374151; }
        .meta span { display: inline-block; margin-right: 12px; margin-bottom: 3px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #d1d5db; padding: 5px 6px; vertical-align: top; }
        th { background: #f3f4f6; font-weight: bold; text-align: left; }
        td.num, th.num { text-align: right; }
        .totals { margin-top: 12px; width: 45%; }
        .footer { position: fixed; bottom: -8px; left: 0; right: 0; text-align: right; font-size: 9px; color: #6b7280; }
    </style>
</head>
<body>
    <h1>{{ $report['title'] ?? 'POS Report' }}</h1>
    <div class="meta">
        <span><strong>Generated:</strong> {{ $report['generated_at'] ?? now()->toDateTimeString() }}</span>
        @foreach(($report['filters'] ?? []) as $key => $value)
            @if(!is_null($value) && $value !== '' && !in_array($key, ['page','per_page','direction','sort_by'], true))
                <span><strong>{{ ucwords(str_replace('_', ' ', $key)) }}:</strong> {{ is_scalar($value) ? $value : json_encode($value) }}</span>
            @endif
        @endforeach
    </div>

    <table>
        <thead>
        <tr>
            @foreach(($report['columns'] ?? []) as $column)
                <th>{{ $column['label'] ?? $column['key'] }}</th>
            @endforeach
        </tr>
        </thead>
        <tbody>
        @forelse(($report['rows'] ?? []) as $row)
            <tr>
                @foreach(($report['columns'] ?? []) as $column)
                    @php($value = data_get($row, $column['key']))
                    <td @if(is_numeric($value)) class="num" @endif>
                        @if(is_array($value) || is_object($value))
                            {{ json_encode($value) }}
                        @else
                            {{ $value }}
                        @endif
                    </td>
                @endforeach
            </tr>
        @empty
            <tr><td colspan="{{ max(1, count($report['columns'] ?? [])) }}">No data found for selected filters.</td></tr>
        @endforelse
        </tbody>
    </table>

    @if(!empty($report['totals']))
        <table class="totals">
            <thead><tr><th>Total Field</th><th class="num">Value</th></tr></thead>
            <tbody>
            @foreach($report['totals'] as $key => $value)
                @if(!is_array($value))
                    <tr>
                        <td>{{ ucwords(str_replace('_', ' ', $key)) }}</td>
                        <td class="num">{{ $value }}</td>
                    </tr>
                @endif
            @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">Generated by POS Enterprise Reporting</div>
</body>
</html>
